"""add bookings

Revision ID: 16db8930401a
Revises: df3dc92e6632
Create Date: 2025-11-20 19:20:41.374159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16db8930401a'
down_revision = 'df3dc92e6632'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
