"""add lock_token to booking

Revision ID: 25120f96f744
Revises: 9fa719fd0425
Create Date: 2025-11-23 13:32:51.927449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25120f96f744'
down_revision = '9fa719fd0425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('bookings', sa.Column('lock_token', sa.String(length=255), nullable=True))
    op.drop_column('bookings', 'ststus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('ststus', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'lock_token')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
