"""add seats table

Revision ID: 8a0f45813c2a
Revises: 6496379e3056
Create Date: 2025-11-20 10:38:30.643095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a0f45813c2a'
down_revision = '6496379e3056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    op.add_column('seats', sa.Column('theatre_id', sa.Integer(), nullable=True))
    op.add_column('seats', sa.Column('row', sa.String(length=5), nullable=False))
    op.add_column('seats', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('seats', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_constraint(op.f('seats_show_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'theatres', ['theatre_id'], ['id'], ondelete='CASCADE')
    op.drop_column('seats', 'seat_number')
    op.drop_column('seats', 'show_id')
    op.drop_column('seats', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('seats', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('seats', sa.Column('seat_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_show_id_fkey'), 'seats', 'shows', ['show_id'], ['id'])
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.drop_column('seats', 'status')
    op.drop_column('seats', 'number')
    op.drop_column('seats', 'row')
    op.drop_column('seats', 'theatre_id')
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seat_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('bookings_show_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###
